---
##More info https://keda.sh/docs/2.7/concepts/scaling-deployments/##
- name: Create a Kubernetes namespace
  k8s:
    name: "keda"
    api_version: v1
    kind: Namespace
    state: present

- name: Add chart repo
  kubernetes.core.helm_repository:
    name: kedacore
    repo_url: "https://kedacore.github.io/charts"

- name: Deploy helm
  kubernetes.core.helm:
    update_repo_cache: yes
    create_namespace: yes
    release_name: keda
    release_namespace: keda
    chart_ref: kedacore/keda
    chart_version: 2.7.2
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"